services:
  - type: web
    name: blogify-app
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "cd src && gunicorn blogify.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: blogify-db
          property: connectionString

databases:
  - name: blogify-db
    databaseName: blogify
    user: blogify
    plan: free
