# Generated by Django 5.0.6 on 2024-06-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_bio_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.CharField(max_length=50),
        ),
    ]
