# Generated by Django 5.0.6 on 2024-06-22 01:40

import users.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_location_post_comment_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null='True', upload_to=users.uploads.user_directory_path),
        ),
    ]
