# Generated by Django 5.0.6 on 2024-06-22 01:50

import users.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.uploads.user_directory_path),
        ),
    ]
