# Generated by Django 5.0.6 on 2024-06-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
