# Generated by Django 5.0.6 on 2024-06-25 11:28

import users.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_post_author_rename_photo_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='blank_profile.jpeg', null='True', upload_to=users.uploads.user_directory_path),
        ),
    ]
