# Generated by Django 5.0.6 on 2024-06-26 09:52

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all():
        if not profile.slug:
            slug = slugify(profile.user.username)
            unique_slug = slug
            num = 1
            while Profile.objects.filter(slug=unique_slug).exists():
                unique_slug = f'{slug}-{num}'
                num += 1
            profile.slug = unique_slug
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
